zn "%SYS"
set $ETRAP="write $ZERROR,! do $SYSTEM.Process.Terminate($JOB,1)" set sc=$SYSTEM.OBJ.LoadDir("/opt/harbor-iris/Harbor","ck",,1) if $SYSTEM.Status.IsError(sc) do $SYSTEM.Status.DisplayError(sc) do $SYSTEM.Process.Terminate($JOB,1)
set $ETRAP="write $ZERROR,! do $SYSTEM.Process.Terminate($JOB,1)" set sc=##class(Harbor.Installer).Install() if $SYSTEM.Status.IsError(sc) do $SYSTEM.Status.DisplayError(sc) do $SYSTEM.Process.Terminate($JOB,1)
write "Harbor extension installed",!
halt
